Anaphory/lexedata

Manual.md

I have reorganized the manual to mirror the script organization.

reorganized manual, added concepticon

---

src/lexedata/importer/cognates.py
src/lexedata/importer/fromexcel.py
test/test_excel_conversion.py

Importer/Cognate wrapped in class

Cognate import parser

---

src/lexedata/importer/cellparser.py
test/test_form_matcher.py

Add test for IPA symbols

---

src/lexedata/exporter/cognates.py
test/data/cldf/minimal/cldf-metadata.json
test/data/cldf/minimal/cognate.csv
test/data/cldf/minimal/cognatesets.csv
test/test_excel_conversion.py

The comments were still missing from the export.

---

src/lexedata/enrich/keep_morpheme_boundaries.py

this looks great to me! all comments made it out of the loop. Lev is reviewing the next version of Arawak cognates!

Keep new judgement information, apart from alignment and segments

---

src/lexedata/enrich/segment_using_clts.py

Implemented some minor changes to segment_using_clts.py and added minimal doctest

Reshaping segments

---

src/lexedata/enrich/segment_using_clts.py
src/lexedata/importer/cognates.py
test/data/cldf/smallmawetiguarani/cognatesets.csv
test/test_concept_guesser.py
test/test_excel_conversion.py

Fix import of list-valued CogSet columns

---

src/lexedata/enrich/keep_morpheme_boundaries.py

move functionality from if __name__ == "__main__" part to proper function

reshaped_morpheme

---

src/lexedata/report/list_homophones.py

turned seed from list_homophones.py into running script. added help part. list_homophones.py runs on arawak data.

Check code

---

.pre-commit-config.yaml
src/lexedata/enrich/segment_using_clts.py
src/lexedata/importer/cellparser.py
src/lexedata/importer/excelsinglewordlist.py
src/lexedata/importer/fromexcel.py
src/lexedata/util.py
test/test_additional_importer.py
test/test_cellparser.py
test/test_form_matcher.py

Add reports (and fix some things we noticed in the process)

Single import report

---

.pre-commit-config.yaml
src/lexedata/cli.py
src/lexedata/enrich/align.py
src/lexedata/enrich/guess_concept_for_cognateset.py
src/lexedata/exporter/cognates.py
src/lexedata/exporter/phylogenetics.py
src/lexedata/importer/cognates.py
src/lexedata/importer/fromexcel.py
src/lexedata/util.py
test/test_additional_importer.py

Should fix #97
@nataliacp I think we should pull this branch tomorrow and see whether it gets rid of all the signatures we saw in #97

Strip author signatures

---

.github/workflows/python-tox.yml
.pre-commit-config.yaml
src/lexedata/exporter/phylogenetics.py
src/lexedata/importer/excelsinglewordlist.py
src/lexedata/types.py
src/lexedata/util.py
test/test_excel_conversion.py
tox.ini

Fix the phylogenetics importer, in particular for multistate characters.
BEAST output is not completely done yet, it wants to add partitions for root-meaning codes.

Fix phylogenetics

---

setup.cfg
src/lexedata/exporter/cognates.py
src/lexedata/report/extended_cldf_validate
src/lexedata/report/extended_cldf_validate.py
src/lexedata/util/__init__.py
test/data/cldf/smallmawetiguarani/cldf-metadata.json
test/test_additional_importer.py

Extended validate

---

.github/workflows/python-tox.yml
src/lexedata/change/construct_cognate_table.py
src/lexedata/enrich/add_free_metadata.py
src/lexedata/enrich/segment_using_clts.py
src/lexedata/exporter/cognates.py
src/lexedata/exporter/edictor.py
src/lexedata/importer/cellparser.py
src/lexedata/importer/cognates.py
src/lexedata/importer/edictor.py
src/lexedata/importer/fromexcel.py
src/lexedata/importer/interleaved.py
src/lexedata/report/extended_cldf_validate.py
src/lexedata/report/nonconcatenative_morphemes.py
src/lexedata/util/__init__.py

And may files with issues I noticed on the way

Fix Edictor ex+import

---

src/lexedata/util/excel.py

Change inheritance structure of cell parsers

---

src/lexedata/importer/excel_interleaved.py
test/test_small_example.py

Add more tests for the small bantu-like dataset

Improve testing

---

src/lexedata/exporter/cognates.py
src/lexedata/exporter/edictor.py
src/lexedata/importer/cognates.py
src/lexedata/importer/edictor.py
src/lexedata/importer/excel_matrix.py
src/lexedata/report/nonconcatenative_morphemes.py
src/lexedata/types.py
src/lexedata/util/__init__.py
test/data/cldf/minimal/cldf-metadata.json
test/data/cldf/minimal/forms.csv
test/data/cldf/smallmawetiguarani/forms.csv
test/test_cognate_exporter.py
test/test_edictor.py
test/test_excel_conversion.py
test/test_na_forms.py

But in the process of that work, also handle other issues that I notice, starting with #224 (Rationale: To write the edictor importer, I needed to export to edictor, and for that I needed a dataset, so :rabbit2: :hole:)

Work on the Edictor importer

---

.readthedocs.yaml
src/lexedata/edit/add_central_concepts.py
src/lexedata/edit/add_segments.py

Fix more issues

---

src/lexedata/cli.py
src/lexedata/exporter/phylogenetics.py

Adresses several points of #263.

Add some more details in phylogenetics exporter.

---

docs/Manual.md

added reports

---

.github/workflows/python-tox.yml
docs/installation.rst
setup.cfg
src/lexedata/report/coverage.py
src/lexedata/report/extended_cldf_validate.py
src/lexedata/report/filter.py
src/lexedata/report/judgements.py
src/lexedata/report/nonconcatenative_morphemes.py
src/lexedata/util/__init__.py
test/test_coverage.py
test/test_extended_validate.py
test/test_na_forms.py
test/test_various_parsers.py

Many small fixes

---

CONTRIBUTING.md
README.md

Be more explicit about installations

---

docs/tour.rst
src/lexedata/cli.py
src/lexedata/exporter/edictor.py
src/lexedata/exporter/matrix.py
src/lexedata/exporter/phylogenetics.py
src/lexedata/report/coverage.py
src/lexedata/report/nonconcatenative_morphemes.py
src/lexedata/report/segment_inventories.py
test/test_various_parsers.py

Noticed while working on #313
Also:
Fix #313

Use Set instead of List for XXXOrFromFile

---

docs/installation.rst
src/lexedata/edit/add_concepticon.py
src/lexedata/edit/add_segments.py

Improve catalog handling, when they are missing

---

src/lexedata/importer/excel_long_format.py
test/test_additional_import.py

Catch and test case without value column

---

src/lexedata/edit/merge_cognate_sets.py
src/lexedata/edit/merge_homophones.py
src/lexedata/edit/simplify_ids.py
src/lexedata/util/simplify_ids.py
test/test_util_simplify_ids.py

Fix simplify_ids

---

src/lexedata/cli.py
src/lexedata/exporter/phylogenetics.py
src/lexedata/importer/excel_long_format.py
src/lexedata/report/homophones.py
src/lexedata/report/nonconcatenative_morphemes.py
test/check_all_versions_match.py
test/helper_functions.py
test/test_additional_import.py
test/test_cellparser.py
test/test_form_matcher.py
test/test_various_parsers.py

Small fixes

---

src/lexedata/importer/excel_long_format.py
src/lexedata/util/excel.py
test/test_additional_import.py
test/test_excel_util.py

Remove header magic

---

src/lexedata/edit/detect_cognates.py
src/lexedata/importer/excel_long_format.py
test/test_cognate_detector.py
test/test_dataset_issues.py

Also the final fixes for multiple languages in one long format table.
Sorry that my feature branches are so messy.

Some improvements on cognate set detection

---

test/test_additional_import.py

Test that only one warning is emitted for a newly added language
